### ISSUE TITLE
攻撃シナリオの表のデザイン崩れ

### ISSUE THREAD

**Issue by sergioya** [acrcdlsd/OWASP#8]
攻撃シナリオ(M1-M10共通)の表のデザインが崩れている。CSSで書かないと上手く行かないかも。

**Comment by acrcdlsd** [comment]
table要素でwidthを設定しました。とりあえずこれで・・・
小さい画面で見ると見にくいかもしれませんが...

**Comment by sergioya** [comment]
OK
